
import { GoogleGenAI, Type } from "@google/genai";
import { StudyConfig, MCQQuestion } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "" });

/**
 * Safely parses JSON from the model response.
 * Handles cases where the model might wrap the JSON in markdown code blocks.
 */
const safeJsonParse = (text: string) => {
  try {
    const cleaned = text.replace(/```json|```/gi, "").trim();
    const parsed = JSON.parse(cleaned);
    return parsed;
  } catch (e) {
    console.error("JSON Parse Error:", e, "Raw text received:", text);
    return null;
  }
};

export const fetchChapters = async (classLevel: string, subject: string): Promise<string[]> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Provide a list of 15 specific chapters for ${classLevel} ${subject} based on the latest 2024-25 syllabus. Return the result as a raw JSON array of strings ONLY.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: { type: Type.STRING }
        }
      }
    });
    
    const chapters = safeJsonParse(response.text || "[]");
    return Array.isArray(chapters) && chapters.length > 0 
      ? chapters 
      : ["Unit 1: Fundamentals", "Unit 2: Core Applications", "Unit 3: Advanced Theory"];
  } catch (error) {
    console.error("Fetch Chapters Error:", error);
    return ["Introduction", "Fundamental Concepts", "Theoretical Framework", "Case Studies", "Final Review"];
  }
};

interface StudyResponse {
  summary: string;
  questions: MCQQuestion[];
  revisionPoints: string[];
}

export const generateEducationalContent = async (config: StudyConfig): Promise<StudyResponse> => {
  const { classLevel, subject, contentType, chapter } = config;
  const isMCQ = contentType === 'MCQs';
  
  const prompt = isMCQ 
    ? `Generate exactly 20 high-quality Multiple Choice Questions for ${classLevel} ${subject}, Chapter: "${chapter}".
       Each question must have: 
       1. 'question' (string)
       2. 'options' (array of 4 strings)
       3. 'correctIndex' (number 0-3)
       4. 'explanation' (string)
       Return the result as a raw JSON array of objects.`
    : `List 10 key revision bullet points for ${classLevel} ${subject}, Chapter: "${chapter}". 
       Focus on exam-critical definitions and concepts. Return as a raw JSON array of strings.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: isMCQ ? {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              question: { type: Type.STRING },
              options: { type: Type.ARRAY, items: { type: Type.STRING } },
              correctIndex: { type: Type.INTEGER },
              explanation: { type: Type.STRING }
            },
            required: ["question", "options", "correctIndex", "explanation"]
          }
        } : {
          type: Type.ARRAY,
          items: { type: Type.STRING }
        }
      }
    });

    const text = response.text || "[]";
    const parsedData = safeJsonParse(text);

    if (!parsedData) {
        throw new Error("Empty or invalid content generated by AI");
    }

    return {
      summary: `Educational summary for ${chapter}`,
      questions: isMCQ ? (Array.isArray(parsedData) ? parsedData : []) : [],
      revisionPoints: !isMCQ ? (Array.isArray(parsedData) ? parsedData : []) : []
    };
  } catch (error) {
    console.error("Content Generation Error:", error);
    throw error;
  }
};
